# Generated by Django 4.0.4 on 2022-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_genre_remove_track_genre_track_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='Trackgenre',
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='base.genre'),
        ),
    ]
