# Generated by Django 4.0.4 on 2022-05-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_track_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_path',
            field=models.FileField(default=1, upload_to='base/upload/'),
            preserve_default=False,
        ),
    ]
