# Generated by Django 4.0.4 on 2022-05-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_track_audiofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audioFile',
            field=models.FileField(upload_to=''),
        ),
    ]
