# Generated by Django 4.0.4 on 2022-05-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='track',
            new_name='track_track',
        ),
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
        migrations.AddField(
            model_name='track',
            name='tracklist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.playlist'),
            preserve_default=False,
        ),
    ]
