# Generated by Django 4.0.4 on 2022-05-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_track_tracklist_track_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
