# Generated by Django 4.0.4 on 2022-05-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='tracklist',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='base.playlist'),
            preserve_default=False,
        ),
    ]
