# Generated by Django 4.0.4 on 2022-05-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_track_tracklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='track_track',
            new_name='tracks',
        ),
    ]
