# Generated by Django 4.0.4 on 2022-05-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_track_track_playlist_tracks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='tracks',
            new_name='track',
        ),
    ]
