# Generated by Django 4.0.4 on 2022-05-23 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0036_rename_track_track_playlist_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_name',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracklist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
