# Generated by Django 4.0.4 on 2022-05-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_playlist_playlist_name_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
    ]
