# Generated by Django 4.0.4 on 2022-05-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_profile_tracklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
