# Generated by Django 4.0.4 on 2022-05-23 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0041_track_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='user',
        ),
        migrations.AddField(
            model_name='track',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
